### ISSUE TITLE
Issue Warning: Cumulative Layout Shifts can result in poor user experiences.

### ISSUE THREAD

**Issue by intermx-nagaraj** [mgechev/ngresizable#19]
When i checked in chrome devtool performance analysis shwoing CLS while resizing element. 
can you improve the performance of this lib.
Tested in: https://mgechev.github.io/ngresizable/
![ng-resize-cls](https://user-images.githubusercontent.com/62890035/85365010-13084700-b542-11ea-974a-3dc0469b7829.png)

**Comment by mgechev** [comment]
That's not performance of the library but in the demo. Since it doesn't use SSR the rendering is entirely client-side and there's a delayed CLS.

I'm not sure how well this library works with latest Angular. There are alternatives I'd recommend you to use. Check this out https://www.npmjs.com/package/angular-resizable-element.
