### ISSUE TITLE
Build fails when run on Windows

### ISSUE THREAD

**Issue by jovermier** [mgechev/ngresizable#9]
When you run "npm run build" in Windows the following error occurs:

'cp' is not recognized as an internal or external command
...

**Comment by mgechev** [comment]
It's a bash script so you may need to run it in bash for windows or cygwin, or a vm.

The ngresizable plugin doesn't aim to provide a build setup but only a resizable plugin. This means that the build is not meant to be run by anyone else except the project's maintainers.

Closing the issue since it's not related to the component itself.
